version: '1.0.{build}'
configuration:
- Release
image:
- Visual Studio 2017
platform: Any CPU
init:
- ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: dotnet --version
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet -d build -c %CONFIGURATION%
test: off
cache: